version: '3.4'

services:
  bonillaapp:
    image: ${DOCKER_REGISTRY-}bonillaapp
    build:
      context: .
      dockerfile: BonillaApp/Dockerfile
    networks:
     - backend
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Guadalajara1*
    networks: 
      - backend

networks:
  backend: {}